### ISSUE TITLE
Support for createHashHistory

### ISSUE THREAD

**Issue by jupl** [FormidableLabs/redux-little-router#102]
I'm interested in wanting to use this library for some projects I'm involved in moving forward. It looks like it currently only uses history's `createBrowserHistory` with HTML5 history. There are some situations beyond my control where I need to use hash routes, which is holding me back from jumping head first into this library. Also I'm not sure about the implementation details but I'm assuming with `createMemoryHistory` this could also be used with React Native?

**Comment by miketeix** [comment]
Does redux-little-router have something like ```createMemoryHistory```?
