### ISSUE TITLE
RelativeFragment with Nested Index

### ISSUE THREAD

**Issue by daGrevis** [FormidableLabs/redux-little-router#114]
These are my defined routes:

``` js
const routes = {
  '/': {},
  '/foo': {
    '/bar': {},
  },
}
```

And here is my JSX:

``` jsx
<RelativeFragment forRoute='/foo'>
  Matches /foo and everything deeper

  <RelativeFragment forRoute='/'>
    Matches /foo and only /foo
  </RelativeFragment>

  <RelativeFragment forRoute='/bar'>
    Matches /foo/bar
  </RelativeFragment>
</RelativeFragment>
```

My question is about this part:

``` jsx
<RelativeFragment forRoute='/'>
  Matches /foo and only /foo
</RelativeFragment>
```

When I navigate to `/foo`, I'd like my app to render:

```
Matches /foo and everything deeper
Matches /foo and only /foo
```

Instead I only see:

```
Matches /foo and everything deeper
```

Why didn't it match `/` route? Is this a bug or is this intended?

Navigating to `/foo/bar` should render:

```
Matches /foo and everything deeper
Matches /foo/bar
```

That part works.

**Comment by mmcgahan** [comment]
I have a similar need - I think this is essentially what the old React Router `<IndexRoute>` would do, and I believe React Router v4 uses an [`exactly` attribute on its Match components](https://react-router.now.sh/Match) to make sure they only render when there's a direct hit on the route pattern.

One compromise workaround is to use `<AbsoluteFragment withConditions={...}>` to get `IndexRoute` behavior, although unfortunately it means you have to hand-write the whole route path (you can't use the 'relative' path context):

```jsx
<RelativeFragment forRoute='/foo'>
  Matches /foo and everything deeper

  <AbsoluteFragment withConditions={location => location.route === '/foo'}>
    Matches /foo and only /foo
  </AbsoluteFragment>

  <RelativeFragment forRoute='/bar'>
    Matches /foo/bar
  </RelativeFragment>
</RelativeFragment>
```

It might get a little simpler if you can use `RelativeFragment` in the same way once https://github.com/FormidableLabs/redux-little-router/issues/115 is addressed.

**Comment by ngbrown** [comment]
Ordering seems to matter too.  If I put the index route last, it is picked up, but if it is first, it renders to the exclusion of deeper routes.

**Comment by geordee** [comment]
I guess there is something to do with ordering. I was struggling with a nested route. I wrote the fragments down in a natural drill-down order and I wasn't getting expected results. After going through @ngbrown 's comment I inverted the order. Now things work.

It does not give me a confidence though.

**Comment by Peping** [comment]
Indeed the first RelativeFragment that matches the URL is displayed. It's caused by the greedy matching introduced by 12.0.0 . Before that, all matching fragments would be rendered. 

I do think this behavior is unintuitive. Maybe we should display the fragment that matches the longest part of the current pathname. 

Example: given the pathname `'/zoo/animals/giraffe/donate'`
```
<RelativeFragment forRoute='/zoo/animals'>
    {/* Current behavior: This is the first matching fragment.*/}
    {/* It will be rendered and all further fragments are ignored.*/}
    <RelativeFragment forRoute='/:name'><AnimalBiography /></RelativeFragment>

    <RelativeFragment><AnimalIndex /></RelativeFragment>

    {/* Proposed behavior: Every time the pathname changes check for the deepest matching url. */}
    {/* Render, if a fragment is the deepest matching one, otherwise ignore. */}
    <RelativeFragment forRoute='/:name/donate'><AnimalDonation /></RelativeFragment> 
</RelativeFragment>
```

**Comment by tptee** [comment]
This finally works in `v13.1.0`! Thanks @kkerr1 !!
