### ISSUE TITLE
RelativeFragment using _only_ `withConditions` never renders

### ISSUE THREAD

**Issue by mmcgahan** [FormidableLabs/redux-little-router#115]
It looks like you cannot use `withConditions` logic with `<RelativeFragment>` without also including `forRoute` - the `store.matchWildcardRoute` will always return `null`, which means [this line](https://github.com/FormidableLabs/redux-little-router/blob/master/src/fragment.js#L124) always results in a `null` render.

The 'fix' is to use `AbsoluteFragment` instead of `RelativeFragment`, but it would be nice if I could just use one kind of fragment across my entire app without having to worry about different behavior outside of how `forRoute` is interpreted.

It would be worth adding a parallel test that uses `RelativeFragment` for both of [these test cases](https://github.com/FormidableLabs/redux-little-router/blob/master/test/fragment.spec.js#L90,L118), unless `RelativeFragment` should never be used in this way.

**Comment by tptee** [comment]
I have a fix upcoming for this in the next major version 🎉

**Comment by tptee** [comment]
This is done in [v14.0.0-0](https://github.com/FormidableLabs/redux-little-router/releases/tag/v14.0.0-0)
