### ISSUE TITLE
PersistentQueryLink: Merge current query data with url-provided querystring

### ISSUE THREAD

**Issue by scottnonnenberg** [FormidableLabs/redux-little-router#132]
Today, both in [12.1.2](https://github.com/FormidableLabs/redux-little-router/blob/e08d7ddf7781a1ae88da3ee9539c16d24acc6f8b/src/reducer.js#L24-L39
) and in the [upcoming v13](https://github.com/FormidableLabs/redux-little-router/blob/74fcd4c2435baa15e96907eb2bf6edba7d2122c1/src/link.js#L47-L57), any querystring on a URL provided to `<PersistentQueryLink/>` supercedes any existing query data in the router state. This doesn't seem right, given the name of the component: _**persistent**_.

I think it should merge existing querystring data with the target querystring data from the URL.

**Comment by adregan** [comment]
I was also expecting merging behavior. I had a use case like this in mind:

current url: `https://someapp.com/products?filter=blue&sort=asc&page=2`

Where a pagination would might simply be:

`<PersistentQueryLink href={{ query={page: 3} }}>3</PersistentQueryLink>`

and the url would update to `https://someapp.com/products?filter=blue&sort=asc&page=3`

**Comment by tptee** [comment]
This'll be a lot easier with the action creators introduced in `v13` 👍

**Comment by tptee** [comment]
Fixed in `v14.0.0-1`. Real release coming soon!
