### ISSUE TITLE
HOC / hoc-little-router

### ISSUE THREAD

**Issue by fabienjuif** [FormidableLabs/redux-little-router#141]
Hi guys !

Once again, nice works with this router, I like it a lot !
And thanks for the version 13.0.0-0 ;)

This issue is about a higher order component that we wrote a friend and I for a buisiness project. We opensourced this hoc here : https://github.com/Trampss/hoc-little-router

With this HOC we can hide (or not) a Component easily based on `TITLE` written in the `routes` objects.
We use the redux state to handle the fact that the route is found or not (by redux-little-router)
We look in parent tree by default, but we can avoid this by passing an option : `{ absolute: true }`.

---

 - What do you think of this HOC ?
 - Do you think it could be a nice idea to 
   * Do a PR in this repository to include it to `redux-little-router` ?
   * Do link it from your doc (to our github page) ?

---

Thank you !

PS : With this HOC we avoid the `Provider` (we have to try `<Link />` to make sure about this) and we avoid the `Fragment` component. We think that the code looks prettier like that.

**Comment by axelson** [comment]
Seems kind of like an abuse of the `title` string. I assume (although I could definitely be wrong!) that the purpose of the title string in `redux-little-router` is to be a human-readable title. Now I can see modifying the meaning of `title` in your specific project, but it would seem odd to pull that usage directly into the core of `redux-little-router`

**Comment by fabienjuif** [comment]
Yeah that what I told me when I use `title`, I hesitated to use a `code` param instead.
But since the `redux-little-router` examples have `title` field, I bet that it was easier to understand this `hoc` if I use this field :)

**Comment by granmoe** [comment]
I don't know about this. What's the big benefit of having the logic to determine if a component gets shown in each component as opposed to just wrapping with `Fragment` so you can easily read and understand it in one place (often with a bunch of similar `Fragment`s in the same `render`)? Then to figure out which components are showing for what routes, you'd have to open up every single component and look at its export. This just seems like a bunch of weird plumbing for a simple use case that redux-little-router already solves elegantly. And to keep your component portable and not tightly coupled to one specific route (prior to wrapping with your HOC), you'd have to maintain a plain version and a HOC-ified version. Just being brutally honest here. I hope I don't sound too mean!

**Comment by granmoe** [comment]
Example with normal redux-little-router:

```
  <div>
    <Fragment forRoute="/foo">
      <Foo />
    </Fragment>
    <Fragment forRoute="/bar">
      <Bar />
    </Fragment>
    <Fragment forRoute="/baz">
      <Baz />
      <Foo />
    </Fragment>
  </div>
```

We can clearly see what components are being shown for what routes. WIth your HOC, it becomes cumbersome to reuse components between routes and to understand how they are composed for any given route.

You'd have:

```
<div>
  <ConnectedFoo />
  <ConnectedBar />
  <ExtraWrapperForRouterPlumbing />
</div>
```

ConnectedBar: `export default router('bar')(Bar)`

ConnectedFoo: `export default router('foo')(Foo)`

Foo: `export default Foo`

ExtraWrapperForRouterPlumbing:

```
<div
  <ConnectedBaz />
  <AnotherConnectedFoo />
</div>
```

ConnectedBaz: `export default router('baz')(Baz)`
AnotherConnectedFoo: `export default router('baz')(Foo)

**Comment by granmoe** [comment]
Perhaps I've missed an obvious use case where the HOC makes sense?

**Comment by fabienjuif** [comment]
Hi @granmoe 

The main purpose of the HOC was to :
 - Simplify our `Fragment `usage when there were a bit buggy. But I think this not the case anymore. So this is not revelant 😃 
 - Use the `title` configuration into routes, so we can change some routes without changing this `title` keys.

Why do we choose an HOC style of coding ? I don't know to be honest. I like that idea that configuration are not into JSX. 

Our application is symply this form :
```
 - src/
   - gui/
      - components/
      - screens/
   - app.jsx
   - 
```

 - `screens/` contains our ... screens ( 😄 ) with their HOC, in a hierarchical way when we can.
 - `components/` contains our components that screens just assembly together.

It seems easy to read to me.
I agree with you about the fact that we need to open screens to see the title route connected to.
But we have a simple convention : the screen directory name is the same of the `title` key.
So we don't need to change / read the hoc configuration.

We don't have any configuration into our components (JSX) nor our container (connected via react-redux).

Thank you for the interest :)

**Comment by granmoe** [comment]
@fabienjuif  OK, that makes sense that you have that convention, and it also helps alleviate the concern I brought up. As always, things make more sense in context :-)

**Comment by tptee** [comment]
Great discussion here! I added hoc-little-router to the README for folks to check out 😃

**Comment by fabienjuif** [comment]
Thank you @tptee 👍
