### ISSUE TITLE
Docs are ahead of published package

### ISSUE THREAD

**Issue by Koleok** [FormidableLabs/redux-little-router#142]
Looks like there have been some updates to how this is installed in the store, namely 
```js
const {
  reducer,
  middleware,
  enhancer,
} = routerForBrowser({ routes });
```

vs

```js
const {
  routerEnhancer,
  routerMiddleware,
} = routerForBrowser({ routes });
```

But the [newest version (13.0.0)](https://github.com/FormidableLabs/redux-little-router/blob/master/package.json#L3) that supports this style of installation has not been published to npm yet as of the time of writing this issue ![badge](https://badge.fury.io/js/redux-little-router.svg)

This is leading to some difficult on-boarding that takes investigation for a teammate of mine right now,  I am excited for the new version but you should probably roll out the package and the docs at the same time.

**Comment by rahulkgupta** [comment]
Would really love to use the new version! thanks.

**Comment by MatthewPikar** [comment]
Just started implementing this package and, for sure, reducer, middleware, enhancer return undefined.  Glad to know I wasn't going insane.

**Comment by tptee** [comment]
Sorry all! New version is out and now the docs are in sync!

**Comment by Koleok** [comment]
@tptee thanks sir!
