### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MrLoh** [FormidableLabs/redux-little-router#143]
Hi, love the library. Unfortunately you don't have any License specified, which is somewhat problematic for using this for commercial products. I'd sugges you adopt the MIT License that redux [uses](https://github.com/reactjs/redux/blob/master/LICENSE.md) as well.

**Comment by tptee** [comment]
Oops, this is definitely meant to be MIT! Will merge in the license.

**Comment by tptee** [comment]
Done! Thanks for catching this! https://github.com/FormidableLabs/redux-little-router/blob/master/LICENSE.md
