### ISSUE TITLE
Question: Usage with react-redux

### ISSUE THREAD

**Issue by james-gardner** [FormidableLabs/redux-little-router#147]
Question: Why can I not use react-redux's <Provider> component in place of the one provided by redux-little-router? It seems superfluous to have to use both: 

```
const renderRoot = (id) => render(
  <RouterProvider store={store}>
    <Provider store={store}>
      <App />
    </Provider>,
 </RouterProvider> 
 document.getElementById(id)
);
```
I'm guessing under the hood they do different things with context. Both bindings are really useful.

**Comment by fabienjuif** [comment]
Hi @james-gardner 

Look at that issue : https://github.com/FormidableLabs/redux-little-router/issues/141
I think the HOC we made agrees with what you say : We don't need the `RouterProvider`, and we don't need `Fragment` anymore 😉 

Please upvote this issue if you like the idea 😃

**Comment by axelson** [comment]
Yeah, that threw me for a loop as well. Also it's doubly confusing because the README doesn't show the `<Provider>` being used alongside `<RouterProvider>`, yet it is in the demo.

**Comment by tptee** [comment]
`<RouterProvider>` is dead in `v14` and above–just make sure you're using `react-redux`'s `<Provider>`, since `<Link>` and `<Fragment>` are both `connect()`ed components.
