### ISSUE TITLE
enhancer(...) is not a function

### ISSUE THREAD

**Issue by ChrisLMerrill** [FormidableLabs/redux-little-router#149]
I am trying to switch the beginnings of a React/Redux app from react-router to redux-little-router by following the Boilerplate section. I've stripped out all the React and anything else not required to reproduce the problem. I'm getting an "enhancer(...) is not a function" error. I've stepped down into the redux-little-router source, but my JS debugging skills don't seem to be up to the task of diagnosing what I've done wrong. Also tried making a JSFiddle, but have not, so far, been able to create something helpful.

First few lines of the stack trace are:
index_bundle.js:6648 Uncaught TypeError: enhancer(...) is not a function
    at createStore (index_bundle.js:6648)
    at index_bundle.js:15338
    at index_bundle.js:14691
    at createStore (index_bundle.js:6648)
    at Object.<anonymous> (index_bundle.js:7714)

The last line corresponds to "const Store = createStore(..." line in the source below.

Is this enough to information to suggest what I'm doing wrong?

TIA!
Chris

```import { combineReducers, compose, createStore, applyMiddleware } from 'redux';
import { routerForBrowser, initializeCurrentLocation } from 'redux-little-router';

const AppStateReducer = (state = InitialState(), action) => {
    console.log("should handle action: " + action.type);
    return state;
};
const InitialState = () => {
    return {"subjects":[], "results":null};
};

const routes = {
    '/': {
        title:"LORAS",
        '/testresult': {
            title: "Loading Test Result",
            '/:id': { title: "Test Result for:"}
        }
    }
};

const {
    reducer,
    middleware,
    enhancer
} = routerForBrowser({
    routes
});

const Store = createStore(
    combineReducers({router: reducer, appReducer: AppStateReducer}),
    InitialState,
    compose(enhancer, applyMiddleware(middleware))
    );

const initialLocation = Store.getState().router;
if (initialLocation) {
    Store.dispatch(initializeCurrentLocation(initialLocation));
}
```

**Comment by fabienjuif** [comment]
Hi @ChrisLMerrill which version do you use ?
You can enhance the code snippets by doing this : 
```
```es6
<your code is here>
a``` (delete the "a")
```

**Comment by ChrisLMerrill** [comment]
I'm have ^13.0.0 in package.json. I just added it (via yarn) a few days ago, so I think that should be very recent?

**Comment by fabienjuif** [comment]
I have very similar configuration with 13.0.0 version and it works.
This is slightly different here : 
```es6
const {
    reducer,
    middleware,
    enhancer
} = routerForBrowser({
    routes,
    basename: '/',
});
```

Since I have a `basename` set

**Comment by ChrisLMerrill** [comment]
I added the basename, but it had no effect on the result.

If my code lacks an obvious mistake, then I guess I need to work on a SSCCE.

**Comment by Wolfhergang** [comment]
I have the same setup and it works, if "enhancer" is not a funtion, then what is it? undefined?

**Comment by ChrisLMerrill** [comment]
I finally tracked this down. I was passing a function that supplied the initial state, rather than the initial state.

```es6
const Store = createStore(
    combineReducers({router: reducer, appReducer: AppStateReducer}),
    InitialState,
    compose(enhancer, applyMiddleware(middleware))
    );
```

should have been 
```es6
const Store = createStore(
    combineReducers({router: reducer, appReducer: AppStateReducer}),
    InitialState(),
    compose(enhancer, applyMiddleware(middleware))
    );
```

**Comment by Wolfhergang** [comment]
Totally missed the arrow function, i usually just define the initial state as constant, so i did not noticed you didn't
