### ISSUE TITLE
Documentation that outlines differences from other routing solutions

### ISSUE THREAD

**Issue by Restuta** [FormidableLabs/redux-little-router#15]
This includes:

* [x] `react-router-redux`
* [x] `redux-router`

Can be taken from:

http://formidable.com/blog/2016/07/11/let-the-url-do-the-talking-part-1-the-pain-of-react-router-in-redux/
http://formidable.com/blog/2016/07/19/let-the-url-do-the-talking-part-2-bargaining-and-acceptance-with-redux-and-react-router/
http://formidable.com/blog/2016/07/25/let-the-url-do-the-talking-part-3-empower-the-url-with-redux-little-router/

There should be a simple explanation of the use-case on when redux-little-router should be used vs above two.

--
I am sure this is planned, but creating this issue so people can subscribe.

**Comment by tptee** [comment]
This is a good idea! I've added the blog series and a couple of blurbs about why `redux-little-router` exists. I'm going to leave this open so I remember to address `react-router-redux` and `redux-router` specifically.

**Comment by tptee** [comment]
Updated with a blurb about the two libraries in `master`!
