### ISSUE TITLE
Problem in Advanced Docs for server rendering: change app.use to app.get 

### ISSUE THREAD

**Issue by benmcmaster** [FormidableLabs/redux-little-router#151]
I noticed that when I reloaded my page on `localhost:8080/about`, `routerForExpress` would put the `/about` in the `basename` instead of the `pathname`. Which would mess up the routes on the browser. However when I changed:
```
app.use('/*', (req, res) => {
```
to
```
app.get('/*', (req, res) => {
```
as it is in the `demo/server/index.js`. It now works and the `pathname` is correct.

Will changing it to `app.get` cause any problems?

**Comment by tptee** [comment]
Done in #152 . Thanks for the PR!
