### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated.

### ISSUE THREAD

**Issue by larsbs** [FormidableLabs/redux-little-router#156]
The latest version of react is giving this warning when using this library. 

![screen shot 2017-04-13 at 10 47 58](https://cloud.githubusercontent.com/assets/1436588/24997363/ad8b7c10-2036-11e7-91f6-c079b9d152af.png)

**Comment by MatthewPikar** [comment]
Ha, was just coming on here to report the same issue.  +1 from me.

Using `"redux-little-router": "^12.1.2"`
