### ISSUE TITLE
Is "push" router api working?

### ISSUE THREAD

**Issue by Wolfhergang** [FormidableLabs/redux-little-router#161]
#I have a simple routing in a small app im developing, Link components work right but i can't make push routing work, are there any special conditions that im not aware of?

im just importing the push generator in a component and straight using it on a function

```
import { push } from 'redux-little-router'

...

myFunction () {
    // Do something
    push('/another_place')
} 
````

**Comment by Wolfhergang** [comment]
Omg.... its an action creator, lets pretend i never asked this jaja, tought it was a direct api to the router reducer

**Comment by tptee** [comment]
No worries 😜
