### ISSUE TITLE
Target being passed to <a> in <Link>?

### ISSUE THREAD

**Issue by Lucretiel** [FormidableLabs/redux-little-router#164]
I was reading through the source code of `<Link>`, and I found this:

https://github.com/FormidableLabs/redux-little-router/blob/master/src/components/link.js#L92-L99

Shouldn't the `target` be passed to the underlying `a` element?

**Comment by kkerr1** [comment]
It would seem to me links with a target are explicitly not handled by RLR, since if you set a target you are generally going to want to browser to handle that action.

**Comment by Lucretiel** [comment]
Yes, that's my point. The problem is that `target` isn't a member of `... rest`, so it doesn't actually get passed to the underlying `<a>` element, and won't actually be handled by the browser.
