### ISSUE TITLE
location state is not persisted for initial route

### ISSUE THREAD

**Issue by gshively11** [FormidableLabs/redux-little-router#165]
https://github.com/FormidableLabs/redux-little-router/blob/master/src/enhancer.js#L34

The location returned by the history listener does not return state (and thus query) for the initial route.  Reproduce using this flow:

1. On a new tab, load a URL with at least one querystring value
2. Perform an action on the page that results in a push to a new url with different query values
3. Press the browser's back button

Expected: the query object should be available on the ROUTER_LOCATION_CHANGED action payload
Result: the query is an empty object (key is undefined and hash is an empty string as well).

I spent a little time trying to track down the root cause, but had to move onto other things, so reproduction steps is the best I can give you at the moment.

**Comment by justrossthings** [comment]
reproduced: [https://giphy.com/gifs/bugshot-l4FGorVhHrrXvHZLO/fullscreen](https://giphy.com/gifs/bugshot-l4FGorVhHrrXvHZLO/fullscreen)

**Comment by justrossthings** [comment]
Reproduced: [https://gfycat.com/ValuableVillainousCanvasback](https://gfycat.com/ValuableVillainousCanvasback)

**Comment by gshively11** [comment]
Workaround for the moment seems to be immediately dispatching a `replace` action using the initial location's pathname and search:

```
const initialLocation = store.getState().router;
if (initialLocation) {
  store.dispatch(initializeCurrentLocation(initialLocation));
  // Hack workaround for https://github.com/FormidableLabs/redux-little-router/issues/165
  store.dispatch(replace(`${initialLocation.pathname}${initialLocation.search}`));
}
```

**Comment by skattyadz** [comment]
While debugging something similar (no `key` set on initial load) I managed to replace the snippet above with:

```js
store.dispatch(replace({}));
```

**Comment by jakewisse** [comment]
@skattyadz: That will wipe out the query string entirely. `packState()` will return:

```js
{
  search: '',
  state: {
    reduxLittleRouter: {
      query: {},
      options: {}
    }
  }
}
```

If you'd rather pass an object to `replace()`, you can do:

```js
dispatch(replace({
  pathname: routerState.pathname
  search: routerState.search
}));
```

**Comment by jakewisse** [comment]
@gshively11's workaround leaves off the hash if there is one. Since I'm not rendering on the server or anywhere that doesn't have `window.location`, I'm just doing:

```js
dispatch(replace(window.location.href));
```

**Comment by tptee** [comment]
Weird, I can't seem to repro this in the demo. Might have to do with the fact that it's SSRing. @justrossthings if you get a chance, can you send me a repro repo? Otherwise I'll try to disable SSR and reproduce in the demo.

**Comment by tptee** [comment]
...wait, that's just `react-redux-boiler` right? I'll clone and investigate

**Comment by justrossthings** [comment]
@tptee probs won't be repro from `react-redux-boiler` as I've changed it a bit, plus it's not using v14 & i imagine the fix for https://github.com/FormidableLabs/redux-little-router/issues/144#event-1134080963 would have fixed this

**Comment by tptee** [comment]
Finally reproduced, even in SSR. This is going to require some refactoring :/
