### ISSUE TITLE
Suggest clarifying if initialStateForSSR is required or not

### ISSUE THREAD

**Issue by shepmaster** [FormidableLabs/redux-little-router#17]
In my intended usecase, I don't have server-side rendering (I don't even have a JS-backed server!), so reading about `initialStateForSSR` is a bit disconcerting. I can't quite tell if I need to use it or if I can leave it out or what. I'm still going to investigate, but clarifying the docs might help others out that have the same question.

Thanks for a new library that puts Redux in the forefront!

**Comment by shepmaster** [comment]
And now I see

> At the bare minimum ... 

Perhaps that can be called out better? Maybe a "bare bones" example distinct from the "bells and whistles" example? Or different organization of each feature? Calling out the "initial state" is a good example (although it could maybe use a more obvious header?).

**Comment by tptee** [comment]
Hi @shepmaster ! We just released `v7.0.0` which removes `initialStateForSSR` entirely. I added an example for client-side-only rendering to the docs:

```
import { compose, createStore } from 'redux';
import { createStoreWithRouter } from 'redux-little-router';

import yourReducer from './your-app';

// Arbitrary data to add to the state tree when a route is
// matched and dispatched. Useful for page titles and other
// route-specific data.

// Uses https://github.com/snd/url-pattern for URL matching
// and parameter extraction.
const routes = {
  '/': {
    title: 'Home'
  },
  '/messages': {
    title: 'Message'
  },
  '/messages/:user': {
    title: 'Message History'
  }
};

// This is an example of initializing the router in a client-only
// single-page app. Passing in at least the `pathname` will allow
// `createStoreWithRouter` to automatically setup the initial state
// for the first browser location.
const clientOnlyStore = createStore(
  yourReducer,
  initialState,
  createStoreWithRouter({
    routes,
    basename: '/example', // optional, the basename for all routes. defaults to '/'
    pathname: '/home', // optional, the initial URL
    query: { // optional, the initial query string object
      ex: 'ample'
    }
  })
);
```

For the initial `pathname`, you can just snag `window.location.pathname` (although you might have to strip out the basename from there if you're using a basename) 😄 

Let me know if that makes sense!

**Comment by shepmaster** [comment]
> you can just snag window.location.pathname

I'm not sure that's correct on it's own. Doing that by itself causes this line to fail:

```js
if (forRoute && matchRoute(location.pathname).route !== forRoute) {
```

because `matchRoute` returns `null`. That happens because my path `/help` is `help` (missing the leading `/`). If I explicitly set `basename` to `""` then it appears to work.

I think marking `basename` and `pathname` as "optional" isn't quite accurate. If I should always be passing in `window.location.pathname`, then it's not truly optional ;-)

**Comment by tptee** [comment]
Hey @shepmaster , does `7.0.1` fix that for you? There was a bugfix merged in from #27

**Comment by shepmaster** [comment]
Strangely, my own case seems to have regressed. I'm back to the original behavior:

1. Can *load* `/` and `/help` and the appropriate page shows up.
1. Clicking on the "help" link changes the URL to the appropriate value, but does not render the correct `Fragment`.

```
$ grep version node_modules/redux-little-router/package.json
  "version": "7.0.1"
```

Setting a breakpoint [inside of `Fragment`](https://github.com/FormidableLabs/redux-little-router/blob/v7.0.1/src/fragment.js#L9), it's called once when the page loads, but not after clicking the link.

**Comment by shepmaster** [comment]
Upgraded to 7.0.2, no change in that behavior.
