### ISSUE TITLE
Don't commit built code

### ISSUE THREAD

**Issue by AndrewRayCode** [FormidableLabs/redux-little-router#174]
Git is for source code, not compiled code :). Git diffs and logs are much harder to read when compiled code is committed, and the repo size is bloated. And Github is not a file host.

**Comment by tptee** [comment]
Hey @AndrewRayCode, we only commit built code in `dist/` to provide a UMD bundle for CDN usage and for people who like that sort of thing. We only build these on tagged releases.

**Comment by ryan-roemer** [comment]
@tptee -- You may want to consider a future ticket of only publishing `dist/` to npm and advising folks to use unpkg. E.g. https://unpkg.com/redux-little-router@13.1.3/dist/

**Comment by AndrewRayCode** [comment]
> Hey @AndrewRayCode, we only commit built code in dist/ to provide a UMD bundle for CDN usage and for people who like that sort of thing. We only build these on tagged releases.

I understand. None of these statements addresses the concerns in this issue.

**Comment by tptee** [comment]
Thanks for your concerns. We'll likely remove `dist/` and recommend `unpkg` soon, but it's not a high priority.
