### ISSUE TITLE
Issues with React.Children.only in v13

### ISSUE THREAD

**Issue by cafreeman** [FormidableLabs/redux-little-router#175]
Hi there!

First off, thank you for making this library! I absolutely love working with it :)

I've been on v12 for a while and am attempting to update to the new version. After updating some of the boilerplate/config stuff, everything seems to be booting fine, but I'm getting an error from (I thin?) my `Fragment` components.

![image](https://user-images.githubusercontent.com/7971393/26978513-62b9f9e0-4cf1-11e7-91be-801154d03cf7.png)

This error seems to be originating from the `Fragment` component itself, and it makes seem like `Fragment` expects to only have a single child at any given time. Is this true? Have the semantics around `Fragment` changed in v13?

If you have any ideas or suggestions, they'd be greatly appreciated!

**Comment by cafreeman** [comment]
Ahhhh, I think I figured it out. `Fragment` doesn't insert a surrounding `div` anymore, so whatever it's wrapping needs to be fully encapsulated.

**Comment by tptee** [comment]
Hey @cafreeman, you're right on the money 😃 We removed the surrounding divs in this release: https://github.com/FormidableLabs/redux-little-router/releases/tag/v13.0.0
