### ISSUE TITLE
Unclear documentation on how to call provideRouter

### ISSUE THREAD

**Issue by shepmaster** [FormidableLabs/redux-little-router#18]
The [README suggests](https://github.com/FormidableLabs/redux-little-router/blob/326e923615b60ae9430a9076712555a3edf83fa9/README.md):

```js
const AppComponentWithRouter = provideRouter(YourAppComponent);
```

The [tests suggest](https://github.com/FormidableLabs/redux-little-router/blob/326e923615b60ae9430a9076712555a3edf83fa9/test/spec/provider.spec.jsx#L21-L24)

```js
provideRouter({
    store: storeFactory(),
    history
})(MagicalMysteryComponent);
```

**Comment by tptee** [comment]
Thanks, good catch! Updated in the README to:

```js
const AppComponentWithRouter = provideRouter({
  store: createYourStore()
})(YourAppComponent);
```

Notice that you don't have to pass `history` anymore in `v7.0.0`!
