### ISSUE TITLE
Preventing navigation?

### ISSUE THREAD

**Issue by cyberhck** [FormidableLabs/redux-little-router#180]
How do I prevent user from navigating away from current page? Say, if he hasn't saved the form, and we'd like to display a dialog, is there a way to do that?

**Comment by justrossthings** [comment]
using `push`,  you could put navigation logic into an action that dispatches to a new route only when user has met page requirements. eg. 

```
export function navigateCheck(data) {
  return (dispatch) => {
    if (data.meets.condition) {
       // navigate
       dispatch(push('/about'))
    } else {
       // throw error
       dispatch({ type: DIDNT_FILL_FORM })
    }
  }
}

**Comment by dpwrussell** [comment]
@justrossthings Unfortunately you'd have to do that for every single navigation element on the page, many of which might come from other components which have no knowledge of the one which contains the form.

I think something deeper is required.

**Comment by cyberhck** [comment]
@dpwrussell exactly the reason and why I wouldn't want to do that. For now I abandoned redux-little-router for our project and went with router5 (great api), where preventing navigation is really good. (You can pass in promises, that'd mean you can display your own dialog and ask for confirmation) :)

**Comment by justrossthings** [comment]
(Looking at the [Router5 API](http://router5.github.io/docs/preventing-navigation.html) for this): Would a helper function on the component, which could be checked by `<Link>` elements to enable/disable navigation be the ideal solution?

**Comment by cyberhck** [comment]
I'm no expert on this, but what if the link doesn't trigger a route change? say we're trying to trigger on a button click After doing something (say after checking permissions), in that case, we're directly dispatching the action.

IMO, the way router5 is done is very different, it treats everything as side effect, when route changes, THEN it changes the URL using plugin, so it's really easy for router5 to do the preventing navigation (with promise as well), since it doesn't really do a redirect, it changes the redux store, before doing that, it checks if there's any handler, if handler says we can't, then it doesn't do the change of store, hence no change of url.

But (not sure if I'm correct), in case of redux-little-router, we make the change of URL, then we listen to the pop event, then we do the routing correctly? in this case, we'd have to check if there's a handler for canDeactivate (or something similar just before doing the redirect), then not actually do the redirect instantly.

I'd suggest: have a router instance which has a hooks object like so: {url: '/path/', canActivate: null} (components would pass their handler), before doing a dispatch, check if '/path' has a handler, then act accordingly, but not changing the URL immediately. Of course, everything needs to be with dispatchers, a Link component shouldn't directly provide a `<a>` element without using dispatcher of course.

Again, I'm no expert on this, so maybe there's a better way of doing this.

**Comment by dpwrussell** [comment]
I am also not an expert on this, but I need this functionality and the best I could do was some middleware.

```js
// Middleware to prevent route actions without confirmation when editing
export const routePrevent = store => next => action => {
  switch(action.type) {
    case PUSH:
    case REPLACE:
    case GO:
    case GO_BACK:
    case GO_FORWARD:
      if (isEditing(store.getState()) && !isNavconfirm(store.getState())) {
        store.dispatch(navConfirm(action.payload, action.type));
        return null;
      }
      break;
  }

  return next(action);
};
```

I then later do this "action replay":

```js
dispatch({ type, payload });
```
Beware that right now this can cause issues because of #196.

Also note that it has serious limitations in that it does not intercept browser back/forward because these go directly to the history.

Ultimately, I think RLR will have to integrate with history.js more closely which is how I suspect that router5 does this, although I have not looked into it as yet, but definitely will for my next application!

**Comment by cyberhck** [comment]
I don't know if your navConfirm will be able to do async preventing, but a good example there :) router5 AFAIK, doesn't use history primarily, (it doesn't care about URL primarily), for router5, navigation info is just another data, which it makes use of, URL changing is the side effect which happens when those nav data changes. (meaning you can use router5 history without any URL at all)

That way, router5 can control preventing navigation very easily :)

**Comment by dpwrussell** [comment]
@cyberhck I'm not entirely sure what you mean by "async preventing", but the way I have this working seems asynchronous to me. Basically if you trigger that middleware (which sits before RLR middleware) then you can not proceed until some specific state has been set. If another `PUSH` for example was dispatched in the meantime, it would also get stuck at this middleware and that would result in no change to the state (as we're still waiting for confirmation of navigation) and would not get to the next middleware, thus no action.

**Comment by cyberhck** [comment]
:D just to be clear, say I've got a dialog which is something like this:
```TypeScript
const dialog = new DialogFactory().withTitle("Your changes aren't saved, are you sure you want to navigate away?").asWarning().build();
const result = dialog.show();
return result;
```

Say when user clicks on cancel, we reject the promise, in that case it shouldn't navigate away, it should work for network requests as well.

That's what I meant by async :)

**Comment by dpwrussell** [comment]
@cyberhck I think that should work, but I do it by having a modal window that displays when navigation is attempted (and was prevented) determined by the `navConfirm` reducer containing the action which needs to be replayed. If they click "cancel", I remove the action stored in navConfirm which causes the modal to disappear. If they click "go", I grab the contents of navConfirm, then clear it, then use the contents I grabbed to replay the original action.

It's not ideal as I said, but it's the best I could do for now.

**Comment by cyberhck** [comment]
Thanks for your help! I might give it a try in a future project when I need something like this. But for now we've got a major app and we want as flexible and clean API as possible, so we're gonna go with router5.

**Comment by tptee** [comment]
Check out the `block` and `unblock` action creators in `v14.3.0`!
