### ISSUE TITLE
Code Splitting / Route Chunking

### ISSUE THREAD

**Issue by mherodev** [FormidableLabs/redux-little-router#183]
My biggest concern with setting up a new routing library is not architecting my way out of code splitting. Now I haven't tried this, but would this sort of approach used alongside React Router work just as well here with Redux Little Router?

Quick and dirty code splitting with React Router v4
https://gist.github.com/acdlite/a68433004f9d6b4cbc83b5cc3990c194

More details from this article:
https://medium.com/@apostolos/server-side-rendering-code-splitting-and-hot-reloading-with-react-router-v4-87239cfc172c

I don't see why not, but I'm coming in a little green. This is described alternatively as "async routes", so I suppose this would be an implementation of async Fragments, in a way.

**Comment by tptee** [comment]
Hi @mherodev! If you're just using `Fragment` and not relying on data attached to static routes, the React Router approach should work just fine. I'll add a demo soon.

If you do use static routes, there's a `replaceRoutes` action creator in `v14.2.0`. You'll want to look at the [advanced docs](https://github.com/FormidableLabs/redux-little-router/blob/master/ADVANCED.md#code-splitting) for usage.
