### ISSUE TITLE
Documentation Questions

### ISSUE THREAD

**Issue by tracker1** [FormidableLabs/redux-little-router#187]
Just curious if the components work with preact, or if they require preact-compat?

Also, do I still need react-redux `<Provider store>` with `<RouterProvider store>` or is it already a composite?

Edit: if a separate provider is needed, maybe you could reuse the react-redux provider, or expose the store the same way the react-redux provider does, so that only one provider component is needed?

**Comment by justrossthings** [comment]
@tracker1 for your 2nd question: you no longer need RouterProvider as of 13.2, just do your Provider like normal:

```
<Provider store={store}>
    <YourDankApp />
  </Provider>
```

**Comment by tptee** [comment]
Hi @tracker1 ! On a quick glance, it looks like `preact-compat` is necessary since we `import React from 'react'`. Let me know if you run into any issues with it!
