### ISSUE TITLE
Suggest offering a `Provider`-esque React element

### ISSUE THREAD

**Issue by shepmaster** [FormidableLabs/redux-little-router#19]
For top-level navigation between pages, I liked this pattern from react-router:

```jsx
<Router>
  <Route />
  <Route />
</Router>
```

With redux-little-router it's a bit more annoying. Since you can't easily have multiple children floating about, I have to use a `div`, something like:

```jsx
const Foo = (
  <div>
    <Fragment />
    <Fragment />
  </div>
);

const Bar = provideRouter({ store, history })(Foo);

const Root = () => (
  <Provider store={store}>
    <Bar />
  </Provider>
);
```

Sadly, Redux' `Provider` doesn't allow for multiple children, which would make this a bit cleaner.

It would be cool to have something like:

```jsx
<Provider store={store}>
  <RouterProvider store={store} history={history}>
    <Fragment />
    <Fragment />
  </RouterProvider>
</Provider>
```

I think having the Higher-Order Function is a good idea, but think that the element might provide a common usecase.

**Comment by tptee** [comment]
The PR above should take care of this for you! I'll put a new release out once it's merged.

**Comment by tptee** [comment]
Added in `v7.1.0`!
