### ISSUE TITLE
Time Travel Broken? :'(

### ISSUE THREAD

**Issue by mherodev** [FormidableLabs/redux-little-router#190]
I'm not sure if this is the subtly of my implementation or an issue with little router or the dev tools, but here's a quick repro:

http://g.recordit.co/OrhgDgSHR1.gif

**Comment by tptee** [comment]
Hi @mherodev ! This should be fixed in the latest alpha (`v14.0.0-1`). Can you try to reproduce with that version? Time travel's working in the demo for me.
