### ISSUE TITLE
Cannot generate new pathname from params

### ISSUE THREAD

**Issue by kxcrl** [FormidableLabs/redux-little-router#192]
First, thanks so much for this package. It's really useful for us.

Unfortunately, I can't seem to only change `params` via `push` and cause the `pathname` to update in any meaningful way.

Given the following

```javascript
params: { postId: '123' }
pathname: 'posts/123'
route: '/posts/:postId'
```

I would expect `push({ params: { postId: '2' } })` to update the `pathname` and subsequently the associated params, but sending `push` with only a `params` argument actually doesn't do anything at all (aside from clearing out any query params). Is this currently working, or is this not yet a feature? I can of course using a little string hackery and regex to generate my own new pathnames, but it just seems like the router should be able to do the same thing on its own.

Thanks!

**Comment by justrossthings** [comment]
when you push are you able to provide a `route` arg? eg. `push({ pathname: '/query', params: { postId: '2' } })`

**Comment by kxcrl** [comment]
So the current workaround that I have now is to generate a new `pathname` from the `route` and the `params` and then just push the updated `pathname`. Since the params are all in the url anyway, it doesn't seem to give me anything to also push the `params` object, right?

What I was hoping to do was to be able to push just the `params` and have it default to the current `route`, or to push the `params` and `route` and in either case have the `pathname` be unnecessary. But it seems like the `pathname` is needed in both cases. Is that right or is it the case that with just `route` and `params` and something is wrong on my end?

**Comment by tptee** [comment]
Hi @kxcrl ! `params` are read-only, as they're extracted _after_ a route matches. Furthermore, the action creators have no way of associating the param keys with the correct URL segments, since they don't know which route is active.

Changing params should be as simple as putting them in the right places in your `pathname`. Let me know if you run into any more trouble!
