### ISSUE TITLE
Can't use `withConditions` without setting `forRoute`

### ISSUE THREAD

**Issue by ch2ch3** [FormidableLabs/redux-little-router#195]
I'm currently using v13.2.0 where the [matching logic in Fragment](https://github.com/FormidableLabs/redux-little-router/blob/v13.2.0/src/components/fragment.js#L107-L113) is wrongly returning `null` because `forRoute` is undefined. In my particular use case it doesn't make sense to define `forRoute` as it's a Fragment I want to apply across multiple routes (but not all children of its parent).

I see that you're already aware of this and it's been rectified in v14.0.0. Do you have an ETA on when this might be released, or if you might add a patch for the current release? 🙂

**Comment by jevakallio** [comment]
Hi @ch2ch3! This fix is already released on the `next` dist-tag, i.e. `npm install redux-little-router@next`.

We are planning on releasing a 14.0.0 stable in the next couple of weeks. There are a few other bugfixes that may require breaking changes, and we want to try to batch breaking changes as much as possible to avoid churn on the consumer side.
