### ISSUE TITLE
Fragment navigation bug

### ISSUE THREAD

**Issue by shepmaster** [FormidableLabs/redux-little-router#20]
Migrating from react-router, I expect to be able to do something like:

```jsx
<Fragment forRoute="/">
  <App />
</Fragment>
<Fragment forRoute="/help">
  <Help />
</Fragment>
```

And then have a link elsewhere:

```jsx
<Link href="/help">Help</Link>
```

Clicking on that link would update the URL and change the view. Right now, it only updates the URL, so I'm clearly missing something. Unfortunately, the tests are mostly focused on the unit level, so it's hard for me to get a big picture view of how things connect.

Something I've really appreciated from other projects is the inclusion of an `examples` directory.

**Comment by tptee** [comment]
Yes, we're in dire need of a real code example, and I'd like to add functional tests on top of that. Stay tuned!

**Comment by tptee** [comment]
If you were running into trouble with `<Fragment>` before, there was a pretty nasty bug in `v6.1.1` you might've hit. Can you try to reproduce it with `v7.0.0`?

**Comment by shepmaster** [comment]
> Can you try to reproduce it with v7.0.0?

Yes, that seems to have been the case. The URL and the view now successfully change. Thanks!

I'll let you leave this issue open or close it at your will.

**Comment by tptee** [comment]
Glad to hear it! I'm going to close this as a bug and make a new issue to track the need for example code.
