### ISSUE TITLE
Fragment forNoMatch is always rendered

### ISSUE THREAD

**Issue by albertogasparin** [FormidableLabs/redux-little-router#208]
I was trying to make the new "404" capability work, but it looks like the fragment gets always rendered.

```js
const routes = { '/': { title: 'Home' } };

<Provider store={store}>
    <div>
        <Fragment forRoute="/">
            <h1>Home</h1>
        </Fragment>
        <Fragment forNoMatch>
            <h1>404</h1>
        </Fragment>
    </div>
</Provider>
```

You can see a running [example of the code I'm using here](
https://runkit.com/albertogasparin/595dfb37d3df4b0012f79be1). It happes with both  `routerForExpress` and `routerForBrowser`.
Am I doing something wrong?

**Comment by tptee** [comment]
Hey @albertogasparin , thanks for the notebook, that's super helpful! I cloned it to give you a working example: https://runkit.com/tptee/5961d0845c279100165f9df6

Looks a little weird without more routes 😬 but hopefully this makes sense!
