### ISSUE TITLE
Route gets basename strip out and breaks matching

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [FormidableLabs/redux-little-router#229]
So I'm using basename `/app` and I have a route which is something like: `/loans/:loanId/apply/start` and redux-little-router will match as `/loans/:loanId"ly"/start` because `/apply` contains `/app`.

It's very easy to reproduce. Just have a basename which is not only `/` and use that anywhere in your router definition.

I'm using version `14.2.0`

**Comment by ZwaarContrast** [comment]
Running into the same issue. Proposed pull request seems to fix this.

**Comment by GuilhermeMedeiros** [comment]
@aisapatino any progress on reviewing this?

**Comment by tptee** [comment]
Fixed in `v14.2.3`!
