### ISSUE TITLE
LOCATION_CHANGED action doesn't remember the query when going back (POP)

### ISSUE THREAD

**Issue by merisbahti** [FormidableLabs/redux-little-router#233]
When moving back to a location with query-parameters, the router seems to have omitted the query-parameters the initial LOCATION_CHANGED-action was called with (even though the POP-action has the query-parameters)

I've included below which actions have to be dispatched to reproduce the issue.
```
ROUTER_LOCATION_CHANGED {param: "foo"}
ROUTER_PUSH {param: "bar"}
ROUTER_LOCATION_CHANGED {param: "bar"}
ROUTER_POP {param: "foo"}  // Why does this have {param: "foo"} and the next action doesn't?
ROUTER_LOCATION_CHANGED undefined  // Expected: ROUTER_LOCATION_CHANGED {param: "foo"}
```

**Comment by jahed** [comment]
Same as #211

**Comment by tptee** [comment]
Yep, duplicate of #211 which is a high-pri bug!
