### ISSUE TITLE
Support React v16

### ISSUE THREAD

**Issue by robertfall** [FormidableLabs/redux-little-router#235]
Hi Team,

Just wanted to start the discussion around supporting React v 16.0.0.

I started looking into it and right off the bat I see that there are a couple of other packages that would also need an update:

```
npm WARN enzyme@2.8.2 requires a peer of react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x but none was installed.
npm WARN react-addons-test-utils@15.5.1 requires a peer of react-dom@^15.4.2 but none was installed.
npm WARN redbox-react@1.4.0 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
npm WARN redbox-react@1.4.0 requires a peer of react-dom@^0.14.0 || ^15.0.0 but none was installed.
```

Before I start digging into this too hard I wanted to check whether there are already plans do to the version bump? I didn't see another issue for it.

**Comment by jcrben** [comment]
A PR is welcome I'm guessing @tptee?

**Comment by stefvhuynh** [comment]
Resolved in https://github.com/FormidableLabs/redux-little-router/commit/7c97af5f87ae8ede5eee9397eb0d94ad2c1cd6a0.
