### ISSUE TITLE
Example of custom Middleware

### ISSUE THREAD

**Issue by fpoirier1** [FormidableLabs/redux-little-router#239]
>Your custom middleware can intercept this action to dispatch new actions in response to URL changes.

I am trying to wrap my head around this little-router. I can't seem to find any example of a custom middleware implementation that would handle the `LOCATION_CHANGED` action. 

Here is my use case : 
1. The user visits the todo list
2. The user clicks the edit button of a todo
3. a PUSH(/todos/{:id}) action is dispatch
4. My custom middleware catches the `LOCATION_CHANGED` action
5. My custom middleware triggers `dispatch(editTodo(id))`
6. The action creator
     6.1 looks the `todo = getState().todos.find(...)` list 
     6.2`dispatch({type:'TODO_SELECTED', todo})` 
     6.3 fetch todo details `fetch('/todo/123')` (using thunk)
     6.4 On fetch, the action creator `dispatch({'TODO_DETAILS_SUCCEED'})`
7. The reducers are thin and update the state based on the action parameters.
8. The `<Fragment>` components renders accordingly to the state and the containers maps the state to the props.

Does that logic make sens ? Is there a simpler way to avoid using a middleware ?

Using this methodology, most of the `dispatch` will come from the custom middleware and the containers will simply use the `push()` function right ?

**Comment by dpwrussell** [comment]
I am just dashing out the door, but potentially this might help you: https://github.com/FormidableLabs/redux-little-router/issues/184#issuecomment-322487785

**Comment by fpoirier1** [comment]
Do you only use the middleware logic to fetch data ? Would it be a good place to do something like this ?

``` 
...
case '/unit/:id':
    store.dispatch(selectUnit(action.payload.params.id)
    break;
...

// actions.js
export const selectUnit = (id) =>{
    return (dispatch) => {
       dispatch(fetchUnit(
           ModelUtils.buildHref('unit', id)
        ));

        dispatch({type: SELECTED_UNIT, id});
    }
}
```

**Comment by dpwrussell** [comment]
If I understand this correctly your action-creator dispatches multiple actions, this is usually fine.

e.g. The one I reference from the unit part of the middleware looks like this.

```js
export const fetchUnit = href => (dispatch, getState) => {
  if (isFetchingHref(href)(getState())) {
    return Promise.resolve();
  }
  dispatch(request(href));

  return api.fetch.unit(href)
    .then(data => {
      dispatch(receiveObjs(href, mergeObjMaps(data)));
      return data;
    })
    .catch(handle404(dispatch)(href));
};
```

**Comment by fpoirier1** [comment]
I guess that answer my question. Thank you so much for your help. I will provided an example of my custom middle soon maybe it will inspire other developers.
