### ISSUE TITLE
There is not enough information in the README

### ISSUE THREAD

**Issue by khmaralex** [FormidableLabs/redux-little-router#274]
Hello guys!

I had a problem with the router yesterday. It's what I wanted:
```
<Fragment forRoute='/'>
  <div>
     <Fragment forRoute='/trackings'>First page</Fragment>
     <Fragment forRoute='/trackings/:trackingId'>Second page</Fragment>
  </div>
</Fragment>
```
But it did not work, router match with **First page** in two cases.
 
I found in the closed issues that It should be like this:
```
<Fragment forRoute='/'>
  <div>
     <Fragment forRoute='/trackings/:trackingId'>Second page</Fragment>
     <Fragment forRoute='/trackings'>First page</Fragment>
  </div>
</Fragment>
```
And it's works!

It would be nice to write about this in the README or fix it (with any order).

Thank you!

**Comment by MiracleBlue** [comment]
Sounds like a great opportunity to contribute!  I'm fairly sure you can directly edit markdown files on github, without needing to clone the full thing locally.  If you want to try that, I'm sure it would be greatly appreciated!
