### ISSUE TITLE
Publish TypeScript types along with package?

### ISSUE THREAD

**Issue by jonasws** [FormidableLabs/redux-little-router#275]
The repository has a `index.d.ts` file, but this is not published along with the library code to NPM> Is this possible to change? Typings are, at the moment, available from DefinitelyTyped, but they are outdated, and it looks like the maintainers of said registry are pretty overwhelmed at the moment.

Maybe it would be a good thing to help them out and ship typedefs with the package itself?

**Comment by parkerziegler** [comment]
I'd definitely support this @tptee @ryan-roemer! Can take some time to do this if folks want to get me up to speed on our `npm` publishing process.

**Comment by ryan-roemer** [comment]
@parkerziegler -- Awesome. @tptee and/or I can definitely walk you through the publish process.

For this repo, I'm guessing:

```sh
$ npm version <major|minor|patch|ACTUAL_VERSION_NUMBER>
$ npm publish
$ git push && git push --tags
```

Also be sure to check with me before doing any of this that we have all the right permissions set up for you 😄

**Comment by parkerziegler** [comment]
Thanks @ryan-roemer!  I'll ping you later today when I free up and we can coordinate 🚀

**Comment by parkerziegler** [comment]
@jonasws The TypeScript defs should now ship with the package as of [`v15.1.0`](https://github.com/FormidableLabs/redux-little-router/releases/tag/v15.1.0). Let me know if you hit any issues with accessing the types. Closing this issue for now.
