### ISSUE TITLE
Fragments don't update upon Link navigation

### ISSUE THREAD

**Issue by brentschroeter** [FormidableLabs/redux-little-router#28]
Updating the Redux store router state by clicking a Link component does not force Fragment components to update. That is, clicking a link causes the page's location to change without causing changes to render.

My quick and dirty fix for my application is to call `forceUpdate()` via a subscriber whenever the Redux store changes. Initializing a subscriber either in the provider or in each fragment seems a likely permanent fix, but where?

**Comment by tptee** [comment]
@brentschroeter is this still happening on the latest version?

**Comment by brentschroeter** [comment]
@tptee Seems to be :/
Example: https://brentschroeter-8e778.firebaseapp.com/
Source: [App.jsx](https://github.com/brentschroeter/portfolio-brent-schroeter/blob/cf15c4baaa205612110bd67521b29559218a1622/js_src/App.jsx)

**Comment by shepmaster** [comment]
Yes, this appears to be the issue I was running into at the end of #17. Here's my report from there:

----

1. Can *load* `/` and `/help` and the appropriate page shows up.
1. Clicking on the "help" link changes the URL to the appropriate value, but does not render the correct `Fragment`.

```
$ grep version node_modules/redux-little-router/package.json
  "version": "7.0.1"
```

Setting a breakpoint [inside of `Fragment`](https://github.com/FormidableLabs/redux-little-router/blob/v7.0.1/src/fragment.js#L9), it's called once when the page loads, but not after clicking the link.

**Comment by tptee** [comment]
@brentschroeter thanks for the repo! I think the problem (in your case at least) is that you're missing `react-redux`. I'll list it as a hard requirement in our README.

I forked your repo and added the `react-redux` boilerplate. `<Fragment>`s work like they should now.

Can you confirm that this works for you as well? @shepmaster could this apply to your usage as well?

**Comment by tptee** [comment]
Probably should've sent you the link 😆 https://github.com/tptee/portfolio-brent-schroeter/blob/master/js_src/App.jsx#L74

**Comment by tptee** [comment]
I've updated the README with a blurb about `react-redux` below:
https://github.com/FormidableLabs/redux-little-router#react-bindings-and-usage

Will leave open until I hear back!

**Comment by brentschroeter** [comment]
Success! Thank you :)
