### ISSUE TITLE
TypeScript: Redundant confliting definition of History interface

### ISSUE THREAD

**Issue by Viniter** [FormidableLabs/redux-little-router#288]
The TypeScript definitions contain a definition of History interface that's not compatible with the one provided by `history` library. 

https://github.com/FormidableLabs/redux-little-router/blob/57a15dbcd88daa95af8f5ad5677e691583b7e5ff/index.d.ts#L126

This causes a typing issue when for example trying to pass custom history to `routerForBrowser()`. You could instead import the interface from `history` and ditch the above mentioned definition.

**Comment by parkerziegler** [comment]
Thanks @Viniter! Appreciate you taking the time to look into those definitions. Just reviewed your PR, testing locally now. Apologies for the late response, we have only so many hands on OSS at once!

**Comment by parkerziegler** [comment]
Fixed by #289.
