### ISSUE TITLE
Hot module reloading causes issues?

### ISSUE THREAD

**Issue by gertsonderby** [FormidableLabs/redux-little-router#291]
This isn't quite a bug report yet, more of a request for if anyone else has seen anything like this, or might know what causes it.

I am encountering an unfortunate interaction, or so it seems, between webpack and react-hot-loader on one side, and redux-little-router on the other, specifically Fragment using `withConditions`. 
It seems like a hot reload of a React component using the hot reload HOC can cause Fragment components to refuse to render their contents.

I have a case where I use two opposed functions for `withConditions` criteria, but neither Fragment will render after a hot reload of either a parent or child of them. This only happens when hot-reloading, and causing any other re-render (i.e. changing any props etc.) causes the right Fragment to render correctly.

Any ideas, thoughts, seen something similar, etc?

**Comment by parkerziegler** [comment]
Thanks for the report @gertsonderby As of December 10, 2018, this project is no longer under active maintenance and we will no longer be moving forward with issue requests. Thank you for helping to make `redux-little-router` better!
