### ISSUE TITLE
Url changes, but component doesn't change on push. Correct component shows up on refresh with correct url.

### ISSUE THREAD

**Issue by liowalex** [FormidableLabs/redux-little-router#293]
I was able to find out the root cause of this problem. Seems like some issue with the new react redux versions. 

Issue manifests with these versions:
```
redux = 4.0.x;
react-redux = 5.1.x;
redux-thunk = 2.3.x;
react = 16.3.x;
```
but not with these versions:
```
react = 15.6.x;
redux = 3.7.x;
react-redux = 5.0.x;
redux-thunk = 2.2.x;
```

**Comment by parkerziegler** [comment]
As of December 10, 2018, this project is no longer under active maintenance and we will no longer be moving forward with issue requests. Thank you for helping to make `redux-little-router` better!
