### ISSUE TITLE
Support redux v4

### ISSUE THREAD

**Issue by Jameskmonger** [FormidableLabs/redux-little-router#297]
When installing `redux-little-router` in a project using `redux@4.0.1`, I get the following warning:

    npm WARN redux-little-router@15.1.2 requires a peer of redux@^3.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by AllBitsEqual** [comment]
Same here. A compat. check and/or update would be great.

In the meantime I'm gonna see if I run into any issues with redux 4 and little-router 15 myself.

**Comment by shepmaster** [comment]
See also #290

FWIW, we've just been using Redux 4 and everything is fine for our usecases.

**Comment by parkerziegler** [comment]
Hey folks, as of December 10, 2018, this project is no longer under active maintenance and we will no longer be moving forward with issue requests. Thank you for helping to make `redux-little-router` better!
