### ISSUE TITLE
A few documentation issues

### ISSUE THREAD

**Issue by dpwrussell** [FormidableLabs/redux-little-router#35]
First let me just say that having used React + Reach Router + React Router Redux for some time I am extremely happy that there is work in progress on an alternative as I basically agree with nearly everything in the trilogy of blog posts. When I learnt React I was convinced that it was the future, and again with Redux... then as soon as I started adding the Router I felt like I'd lost a lot of the things I'd liked in the first place.

I think there is a mistake when saying:
> Like React Router's `<Provider>`, you'll want to wrap `provideRouter` around your app's top-level component like so. (fixed in #37)

I think this should probably say `Router` not `Provider` as that is the part of React Router that this seems to resemble. `Provider` is from `react-redux` and is definitely still needed, which I think also needs reinforcing.

Keep up the good work, I will be testing this as it develops, happy to help in any way I can, and look forward to reaching the point when it can be used in production.

**Comment by tptee** [comment]
@dpwrussell would you mind splitting these out? Easier for us to keep track of progress 👍

**Comment by dpwrussell** [comment]
Resolved in #37

**Comment by tptee** [comment]
Sweet, thanks so much! Will be tackling docs updates over this week.
