### ISSUE TITLE
providerRouter/RouteProvider component must connected to router

### ISSUE THREAD

**Issue by dpwrussell** [FormidableLabs/redux-little-router#38]
It isn't really documented that the component made with `provideRouter` or `RouterProvider` must be connected to redux with a `mapStateToProps` function that returns an object containing `router`. The docs mention that it can be used to get at router state, not that it's mandatory.

This should probably make the example something like:
```jsx
const store = createYourStore();

const App = () => {
  return (
    <RouterProvider store={ store }>
      <YourComponent />
    </RouterProvider>
  );
};

const ConnectedApp = connect(
  state => ({
    router: state.router
  })
)(App);

ReactDOM.render(
  <Provider store={ store }>
    <ConnectedApp />
  </Provider>
  document.getElementById('root');
)
```

Split out from #35

**Comment by tptee** [comment]
I think I'm going to have `<Provider>` do the `connect()`ing automatically. Less boilerplate, less docs! 😄 I'll keep you posted.
