### ISSUE TITLE
createStoreWithRouter pathname not optional

### ISSUE THREAD

**Issue by dpwrussell** [FormidableLabs/redux-little-router#40]
In `createStoreWithRouter` the docs say:

```pathname: '/home', // optional, the beginning URL```

I don't think that is accurate, as if you comment out `pathname`:

> create-matcher.js:24 Uncaught TypeError: Cannot read property 'split' of undefined

Split out from #35

**Comment by tptee** [comment]
I've updated the docs to clarify that `pathname` is required everywhere _except_ for rehydrating the client after a server render:

```js
createStoreWithRouter({
  // The configured routes. Required.
  routes,
  // The basename for all routes. Optional.
  basename: '/example',
  // The initial URL. Required in all cases except for when
  // rehydrating the state tree on the client after a server render.
  pathname: '/home',
  // The initial query string object. Optional.
  query: {
    ex: 'ample'
  }
})
```

Hope that clarifies things!
