### ISSUE TITLE
Documentation on exposed actions.

### ISSUE THREAD

**Issue by kriuz** [FormidableLabs/redux-little-router#44]
The readme only mentions `LOCATION_CHANGED`. It'd be helpful if there was documentation on the other actions exposed and what kind of payload they expect.

**Comment by dpwrussell** [comment]
Might be worth generalising this issue slightly and including the creation and exposure of action creators for route transitions?

**Comment by tptee** [comment]
This is definitely a good idea, but I want to figure out the broken wackiness in #36 before encouraging their use 😬

**Comment by sehcheese** [comment]
@tptee Now that you've resolved [#36](https://github.com/FormidableLabs/redux-little-router/issues/36), will this be on the horizon? Is `ROUTER_PUSH` the right action type as @BigBuckBunny suggests in [#87](https://github.com/FormidableLabs/redux-little-router/issues/87). That one doesn't seem to work for me. Thanks for your help!

**Comment by sehcheese** [comment]
Actually I just got it working! My middleware had to be farther right in my `compose()`. I was able to infer a lot about the available actions in action-types.js. But looking forward to some documentation. Thanks for this library!

**Comment by BigBuckBunny** [comment]
In reviewing comments in #87 on the proper action type, a review of the history actions might help some people.

Depending upon your App and your users expectation, you have to  consider what PUSH and REPLACE actually do to your history stack. In middleware.js the history actions are used:
 case PUSH:
    history.push(action.payload);
    break;
  case REPLACE:
    history.replace(action.payload);

By using PUSH you allow your users to use the browser's back button with the expectation of returning to where they were. REPLACE will remove the previous location messing with their minds, sorta like the new react-router. (By the way I love this router)

Sitepoint setup a [demo page](http://blogs.sitepointstatic.com/examples/tech/history-pushstate/index.html?state=1) with a [related article](https://www.sitepoint.com/javascript-history-pushstate/) to view what happens, here's my output and you can see 'three' disappeared.

History information log
=======================
pushState 1: {"state":1,"message":"one"}
pushState 2: {"state":2,"message":"two"}
pushState 3: {"state":3,"message":"three"}
replaceState 4: {"state":4,"message":"four"}
pushState 5: {"state":5,"message":"five"}
Location: http://blogs.sitepointstatic.com/examples/tech/history-pushstate/index.html?state=4, state: {"state":4,"message":"four"}
Location: http://blogs.sitepointstatic.com/examples/tech/history-pushstate/index.html?state=2, state: {"state":2,"message":"two"}
Location: http://blogs.sitepointstatic.com/examples/tech/history-pushstate/index.html?state=1, state: {"state":1,"message":"one"}

So PUSH has more potential to keep your users sane if they hit the Back button and REPLACE has it place in whatever context of the universe your working on that does not mess up the users.

**Comment by tptee** [comment]
Action creators added and documented in `v13.0.0`! Check 'em out here: https://github.com/FormidableLabs/redux-little-router#provided-actions-and-state
