### ISSUE TITLE
Fragments do not get updated

### ISSUE THREAD

**Issue by marcselman** [FormidableLabs/redux-little-router#55]
Hi,

I'm using the latest version 8.0.0.

I create my store like this:
```js
let store = createStore(
	rootReducer,
	initialState,
	createStoreWithRouter({
		routes,
		pathname: '/',
		forServerRender: typeof window == 'undefined'
	})
);
```

And my root element is:
```html
<RouterProvider store={store}>
	<Provider store={store}>
		<App />
	</Provider>
</RouterProvider>
```

I have some testing elements like this:
```html
<div>
	<Link href='/messages'>Go messaging!</Link>
	<Fragment forRoute='/messages'>
		<div>
			We're messaging!
			<Link href='/'>Go home!</Link>
		</div>
	</Fragment>
</div>
```

When I click the link the URL changes but the fragment stays the same untill I manually force a rerender.

PS: Also it looks like Fragment can only have one child at max, why is that?

Thanks,
Marc

**Comment by dpwrussell** [comment]
To answer the PS. It can definitely take multiple children.

From https://facebook.github.io/react/docs/reusable-components.html
>     // Anything that can be rendered: numbers, strings, elements or an array
    // (or fragment) containing these types.
    optionalNode: React.PropTypes.node,

**Comment by marcselman** [comment]
I agree but somehow I receive an error when having more than one child:

```html
<Fragment forRoute='/messages'>
	<div>more</div>
	<div>
		We're messaging!
		<Link href='/'>Go home!</Link>
	</div>
</Fragment>
```

`Fragment(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.`

**Comment by marcselman** [comment]
Thanks to the just posted sample files I was able to find the problem.
I wrapped <RouterProvider> around <Provider> but it should have been the other way around.
Now it works!

**Comment by tptee** [comment]
Glad that helped! Sorry I didn't get to this sooner!
