### ISSUE TITLE
Question: Handling basic page-style routing

### ISSUE THREAD

**Issue by Connorelsea** [FormidableLabs/redux-little-router#58]
How would we go about handling fairly basic page style route handling when a user initially visits the application. Routes such as (home, about, feed, messages, etc.). I feel like in React Router, I can specify those fairly easily by doing something such as:

```
<Route path="/" component={App}>
  <Route path="home" component={Home}/>
  <Route path="about" component={About}/>
  <Route path="about" component={Messages}/>
  <Route path="about" component={Feed}/>
</Route>
```

In redux-little-router would I simply have a singular parent component that conditionally renders children (Home, About, Messages, Feed) based on URL state? If so, are there any examples of this. If not, how would I go about doing something like this.

Thank you.

**Comment by tptee** [comment]
Hey there! We're preparing a release that makes this a little easier, so I don't want to give you an outdated answer. Hang tight a day and I'll make this more clear!

**Comment by Connorelsea** [comment]
Thanks @tptee, I appreciate it. Excited for more info on this, as it seems React Router and this library are going through some changes.

**Comment by caesarsol** [comment]
Waiting for it as well! ;)

**Comment by tptee** [comment]
Now that `<RelativeFragment>` is out, this is a lot easier! I updated the docs with the following:

`<RelativeFragment>` makes basic component-per-page navigation easy:

```js
<Fragment forRoute='/'>
  <Fragment forRoute='/home'><Home /></Fragment>
  <Fragment forRoute='/about'><About /></Fragment>
  <Fragment forRoute='/messages'><Messages /></Fragment>
  <Fragment forRoute='/feed'><Feed /></Fragment>
</Route>
```

(The key here is that you pass your component as a child element rather than as a class like you would with v3 of React Router.)

Let me know if that's not clear enough and I'll reopen! Enjoy!
