### ISSUE TITLE
404 Routes

### ISSUE THREAD

**Issue by glenarama** [FormidableLabs/redux-little-router#62]
Im wondering if there is a simplified method for checking all routes and 404 routes, I have found the following to work, but it would be ideal to have 404 capability available via a fragment:

All routes (Not sure why this works actually):

```
<Fragment forRoute=''>
  <p>Matches all routes</p>
</Fragment>
```

No route matches:

```
const App = (
  context: {
    router: RouterContext
  }
) => {
  const { matchRoute } = context.router.store;
  const matchResult = matchRoute(location.pathname);
  if(!matchResult) {
    return( <div> 404 error </div>)
  } else {
   return( <div> Application </div>)
 }
}
```

**Comment by tptee** [comment]
Hey there! I'll be thinking about what a 404 API would look like, shouldn't be too hard. As for an "all routes" fragment, we have a new `<RelativeFragment>` coming in our next release that should solve this nicely. I'll ping you when it's ready 😃

**Comment by glenarama** [comment]
Great - thanks for looking at this. 
Another approach would be a withoutRoute='true' on a Fragment. The Fragment could add a check for that in the no routes test and allow through if set.

**Comment by karlguillotte** [comment]
Any thoughts for 404s?

**Comment by benmcmaster** [comment]
Hey @tptee is there a way to do 404 Not Found routes? I would expect a configuration like this:
```
  render () {
    return (
      <Fragment forRoute='/' className={styles.appRoot}>
        <div>
          <Navigation />
          <div>
            <Fragment key='/work' forRoute='/work'>
              <Work />
            </Fragment>
            <Fragment key='/about' forRoute='/about'>
              <About />
            </Fragment>
            <Fragment key='/' forRoute='/'>
              <Home />
            </Fragment>
            <Fragment key='/*' forRoute='/*'>
              <NotFound />
            </Fragment>
          </div>
        </div>
      </Fragment>
    )
  }
```
...where routes would match starting from the first Fragment like a case statement... If no routes matched it would fall into the last one? Is that how it works?

**Comment by mherodev** [comment]
Is there a demo or snippet of 404 routes somewhere?

I don't know if the solution provided here works any longer with the latest update.

**Comment by tptee** [comment]
Sorry this took so long to get official support! As of `v14.0.0-3` you can use `<Fragment forNoMatch>` to replicate this behavior. See [here in the demo](https://github.com/FormidableLabs/redux-little-router/blob/master/demo/client/demo.js#L79).
