### ISSUE TITLE
Location Descriptor

### ISSUE THREAD

**Issue by caesarsol** [FormidableLabs/redux-little-router#63]
The link that should explain what a Location Descriptor is, that's broken and I couldn't find anything like it in the main page of the `history` project:

https://github.com/FormidableLabs/redux-little-router/blame/master/README.md#L228

In particular, I didn't understand if I could specify an URL as an object with dynamic segments not substituted:

```
// In a standalone file, such as /routes.js
const MESSAGES_URL = '/home/messages/:user'

// In a normal component's file
<Link className='anything' href={{
  pathname: MESSAGES_URL,
  params: {
    user: 'caesarsol'
  },
}}>
```

**Comment by caesarsol** [comment]
PS: This project is exactly what I was waiting for! (Or at least going to write it myself)

**Comment by tptee** [comment]
Whoops, the new version of `history` came out and broke that link 😆 I'm on it!

**Comment by tptee** [comment]
Fixed! Thanks for catching that!
