### ISSUE TITLE
Router state's previous value is undefined

### ISSUE THREAD

**Issue by nawatts** [FormidableLabs/redux-little-router#68]
The reducer copies the value of the router state's `current` key to `previous` when a LOCATION_CHANGED event is received. However, the `current` key was removed in 862ec14b7b2f3dfa99e42beb490a81a2ca8d0267.

**Comment by tptee** [comment]
Fix happening in https://github.com/FormidableLabs/redux-little-router/pull/70, just need to fix a test tonight 👍

**Comment by tptee** [comment]
Fixed in `v9.0.2`!
