### ISSUE TITLE
Demo | Refreshing nested example is KO

### ISSUE THREAD

**Issue by fabienjuif** [FormidableLabs/redux-little-router#75]
Hi,

There is a bug in the client demo, adding `--history-api-fallback` doesn't fix the problem.

To reproduce : 
- `npm run demo`
- Click on `nester`
- The URL is equals to `http://localhost:3000/this/is/nested`
- Refresh or open a new tab with this URL : `http://localhost:3000/this/is/nested`
- **There is no result**

**Comment by skurger** [comment]
Is there a work around for this or a fix in the works?  I am trying to move away from react-router but this is a non-starter.

**Comment by tptee** [comment]
You can run `npm run start-ssr-demo` for an example that works on all routes. I believe there's some active bugs in `historyApiFallback` for the webpack dev server 😬

**Comment by Peping** [comment]
@tptee Care to elaborate what bugs could be the cause? I don't really want to give up webpack-dev-server, its hot-reloading and other conveniences, so I'd rather see this fixed, be it on the redux-little-router front, the webpack-dev-server front or any other.

**Comment by tptee** [comment]
The nested example is gone from the demo, but looks like as of webpack 2 there's ways to customize the fallback to make it work: https://webpack.js.org/configuration/dev-server/#devserver-historyapifallback
