### ISSUE TITLE
Immutablejs compatibility

### ISSUE THREAD

**Issue by nihaux** [FormidableLabs/redux-little-router#77]
Hello, I like the approach you take with this router :)
Do you plan on implementing immutablejs compatibility ?

I made it work in my project by patching store-enhancer.js in my project (using set/get/delete instead of _extends({},...)
https://gist.github.com/Nihaux/0ac0d5e4e7bdc82be78bcb83cbc2fd9e

What do you think would be the best approach to implement this behaviour ? I could work on the PR if needed.

thx

**Comment by teunsteenbekkers** [comment]
Is there a way to use an immutable store at this time?

I'm kind of stuck on this issue right now. Pondering if it'd be wise to go with a non-immutable store with immutable properties for the time being.

Does anyone have any ideas regarding this issue? :-)

**Comment by granmoe** [comment]
I'd also love to have immutable js compat. Haaalp!

**Comment by JustFly1984** [comment]
The main bummer right now with all routers, react-router, redux-little-router too is that there is no support of Immutable.Record as rootReducer's initialState. https://medium.com/azendoo-team/immutable-record-react-redux-99f389ed676
For the state it is important to be immutable, and as far as I know, only `immutable.js` provides Structural sharing. Which is very good performance optimization on large collections.

The issues starts when you coming to API. If you use `Immutable.Map` or `List`, you need to use `getIn`/`set` api to fetch data from the state in mapPropsToState, but then you use `Immutable.Record`, there is API similar with Native JS API.

I think there should be some kind of middleware to update/fetch location in redux.
