### ISSUE TITLE
unserializable route properties

### ISSUE THREAD

**Issue by dpwrussell** [FormidableLabs/redux-little-router#79]
The approach that I took to solve this problem was to encourage the use of `matchRoute`. I memoized the function returned by createMatcher so it can be called many times without penalty. I think it's the data in the matched route that is pertinent, not all the data in routes, plus then it's a lot easier to get at. Especially given that the user may be using a custom matcher and/or `routes` definition.

``` jsx
const _X = (props, context) => {
  const { router } = props;
  const { router: { store: { matchRoute }} } = context;
  const r = matchRoute(router.pathname);
  return <h1>r.somedata</h1>;
};

_X.contextTypes = {
  router: React.PropTypes.object
};

const X = connect(state => ({ router: state.router }))(_X);
```

This could be wrapped up into something like `connect` perhaps so all that code doesn't need to be repeated whenever the matchedRoute is needed.

This works out quite well for custom middleware taking advantage of the router as well. I do this by creating my middleware with a closure of matchRoute.

``` js
const codeSplitFactory = matchRoute => store => next => action => { ... }
```

Happy to PR this: https://github.com/dpwrussell/redux-little-router/tree/routeMatch

Also, I didn't completely follow the purpose of this:

``` js
    // Ensure that the router props from connect()
    // actually get to the child component(s)
    return cloneElement(this.props.children, {
      router: {
        ...routerState,

        // This is a hack to allow routes to define
        // unserializable things like components
        result: store.routes[routerState.route]
      }
    });
```

I don't understand why you would pass the router (and result) as properties to the children. Surely part of the point in storing router state in redux is to allow the user to connect to redux if they want to get at that data. I.e. they do a `connectStateToProps`.

**Comment by tptee** [comment]
> The approach that I took to solve this problem

Sorry, I'm not quite following...what's the problem being solved?

> Also, I didn't completely follow the purpose of this:

So this is a hack we used internally for a specific use case...it's intentionally undocumented, pretend it's not there 😬

**Comment by dpwrussell** [comment]
The problem of having access to unserializable properties of routes in components via `conenctStateToProps` and in middleware. I'm proposing that it is a better recommendation to use `matchRoute` than `routes`.

**Comment by tptee** [comment]
I think we're going to try avoiding unserializable route properties for now. I'll let you know if that decision changes!
