### ISSUE TITLE
Change state whenever query parameters change, even if pathname is unchanged

### ISSUE THREAD

**Issue by mike-marcacci** [FormidableLabs/redux-little-router#90]
Right now, if a query parameter is changed but the pathname remains the same, the reducer does not persist the state.

Added PR #89.

BTW, mega 👍  on this package, it's been deeply needed.

**Comment by mike-marcacci** [comment]
I can't assign labels to issues...

**Comment by tptee** [comment]
Fixed in `v10.0.0`!
