### ISSUE TITLE
Calm down the robot

### ISSUE THREAD

**Issue by mike-marcacci** [FormidableLabs/redux-little-router#91]
In preparation for the bot: label this a "bug"

This is an absolutely awesome project, and I can tell it's going to gain traction quickly... but the `gitmagic-bot` (at least with its current settings) is really going to discourage community involvement.

I'd like to kindly suggest turning it down a notch or two.

**Comment by mike-marcacci** [comment]
Case in point: my title ***IS*** in the imperative, present tense... and I now have 8 or so emails from it...

**Comment by tptee** [comment]
Didn't realize how obnoxious the defaults were, just axed the entire thing 👍

**Comment by mike-marcacci** [comment]
Awesome! Thanks – I wouldn't be surprised if they were trying to show off all their features :)

**Comment by tptee** [comment]
It's effective marketing if it makes me stop using it entirely, right? 😜 

I deleted all the noisy bot comments on your PR too 👍
