### ISSUE TITLE
Enhance replaceReducer or don't enhance reducer

### ISSUE THREAD

**Issue by etienne-dldc** [FormidableLabs/redux-little-router#93]
Hi,

When we call `replaceReducer` on store, the `routerReducer` is not injected.
I think you should enhance `replaceReducer` to re-inject `routerReducer` or simply don't enhance `reducer` and ask to users to manually add `routerReducer` in they reducer.

Note that this is not blocking because the package expose the `routerReducer` so if someone else have trouble with `replaceReducer`, you just have to inject the `routerReducer` yourself : 

``` js
import { routerReducer } from 'redux-little-router';

store.replaceReducer(combineReducer({
  router: routerReducer
}));
```

**Comment by tptee** [comment]
`v13.0.0` no longer enhances the reducer, so we're set!
