### ISSUE TITLE
Add a way to style the div that wrap children or use React.Children.only

### ISSUE THREAD

**Issue by etienne-dldc** [FormidableLabs/redux-little-router#94]
Hi,

It would be a good thing to be able to add style to the `div` that  wrap `props.children` in fragment.

Or maybe a better approach would be to replace `return <div>{children}</div>;` by `return React.Children.only(children);` to throw an error if children contain more than one item.
This would also avoid adding an useless `div` in the case of a single children and we can still do this if we want to render more than one component in a fragment:

``` js
<Fragment>
  <div>
    <MyFirstComponent />
    <MySecondComponent />
  </div>
</Fragment>
```

**Comment by tptee** [comment]
Changed in `v13.0.0`!
