### ISSUE TITLE
Fragment stateless components return null causing errors in React < 15.0

### ISSUE THREAD

**Issue by dannyshaw** [FormidableLabs/redux-little-router#97]
Returning `null` from functional stateless components was only introduced [in React 15](https://facebook.github.io/react/blog/2016/04/07/react-v15.html#functional-components-can-now-return-null-too).

I'm seeing `Uncaught TypeError: inst.render is not a function` in 14.8 for Fragments of unmatched routes.

`package.json` indicates `redux-little-router` supports down to React 14.

What's the position here?

**Comment by tptee** [comment]
With React 16 not far away, I'm tempted to drop `0.14` support. Are you still stuck on it? A workaround is to use simple conditionals against the router state–we actually do this in some internal projects because, well, `Fragment` is pretty half-baked 😆

**Comment by dannyshaw** [comment]
Yeah not stuck, discovered this package wasn't right for us. Cheers.
Dropping 0.14 seems the right way to go IMO

**Comment by dannyshaw** [comment]
Sorry I'll let you resolve this with dropping 0.14 support if that's what you want to do.

**Comment by tptee** [comment]
With React 16 around the corner, I think it's safe to close this out 👍
