### ISSUE TITLE
<Link /> href ignores query params

### ISSUE THREAD

**Issue by mike-marcacci** [FormidableLabs/redux-little-router#98]
I would expect the following:
```html
<Link href='/path?key=value'>Text</Link>
```
to render:
```html
<a href='/path?key=value'>Text</a>
```
but instead, we get:
```html
<a href='/path'>Text</a>
```

Clicking on the rendered anchor only directs the browser to `/path`.

**Comment by tptee** [comment]
Yeah, that's a reasonable expectation! For now, you can do this:

```js
<Link href={{
  pathname: '/path',
  query: { key: value }
}}>
  Text
</Link>
```

I'll leave this open since either should be expected to work 👍

**Comment by mike-marcacci** [comment]
Hmm, the workaround appears to behave the same here.

**Comment by tptee** [comment]
Bummer! I'll look into this tomorrow.

**Comment by Aweary** [comment]
Looks like two separate issues from what I can see. For paths as strings, `normalizeHref` ignores anything but `basename` and `pathname`. For paths as location objects, `history.createLocation` seems to stripping the query all together. Might be an issue with the `useQueries` enhancer?

I'm happy to look into this one 😃

**Comment by tptee** [comment]
That'd be awesome, thanks!

We eventually should upgrade to history v4, I've always run into trouble with the basename and query enhancers. It'd simplify a lot of the link code 😀

**Comment by Aweary** [comment]
@tptee PR up at #100 😄 I can look into what it would take to upgrade to history v4.

**Comment by tptee** [comment]
That'd be sick! Biggest issue I know of is that the memory history doesn't support basenames anymore in v4...
