### ISSUE TITLE
Expose onClick handler separate from Link's <a>

### ISSUE THREAD

**Issue by divmain** [FormidableLabs/redux-little-router#99]
We may want access to the same `onClick` handler that is passed to the `<a>` tag [here](https://github.com/FormidableLabs/redux-little-router/blob/master/src/link.js#L121-L128).  This should include all location normalization, query-state persistence, etc. and will allow non-`a` elements to interact with the router in a first-class way.

**Comment by tptee** [comment]
The new navigation action creators in `v13.0.0` handle all the goodies from the `onClick` handler! Huzzah!

**Comment by divmain** [comment]
Thanks @tptee!!!
